# Generated by Django 5.2.1 on 2025-05-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
