# Generated by Django 5.2.1 on 2025-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_demo_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(),
        ),
    ]
